import { useState } from 'react'
import Layout from '@/components/layout'
import type { NextPage } from 'next'
import Head from 'next/head'
import { Textarea, Button } from '@nextui-org/react'

const Home: NextPage = () => {
  const [pasteContent, setPasteContent] = useState('')

  const submitPaste = async () => {
    const res = await fetch('/api/paste', {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        content: pasteContent,
      }),
    })

    const paste = await res.json()

    window.location.href = `/paste/${paste.id}`
  }

  return (
    <Layout>
      <Head>
        <title>Create Remix App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Textarea
        labelPlaceholder="write your paste here :)"
        value={pasteContent}
        onChange={(e) => setPasteContent(e.target.value)}
      />

      <Button onClick={submitPaste}>Paste It!</Button>
    </Layout>
  )
}

export default Home
